baseURL = "https://shan.tax"
copyright = "Shan Sun"
languageCode = "en-gb"
publishDir = "public"
theme = "cactus"
title = "Shan Sun"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
colortheme = "white"
dateFormat = "2006-01"
description = "Reflections on tax, tax technology and more."
logo = "images/robot.png"
rss = true
showAllPostsOnHomePage = true
[[params.social]]
link = "https://github.com/bobbleoxs"
name = "github"
[[params.social]]
link = "http://linkedin.com/in/xiaoshansun"
name = "linkedin"
[markup.goldmark.renderer]
unsafe = true
